<?php

namespace ContainerJUqqG8p;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HYEQ914Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HYEQ914' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HYEQ914'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agriculteurRepository' => ['privates', 'App\\Repository\\AgriculteurRepository', 'getAgriculteurRepositoryService', true],
        ], [
            'agriculteurRepository' => 'App\\Repository\\AgriculteurRepository',
        ]);
    }
}
