<?php

namespace ContainerJUqqG8p;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4XFgzjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O4XFgzj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O4XFgzj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'agriculteur' => ['privates', '.errored..service_locator.O4XFgzj.App\\Entity\\Agriculteur', NULL, 'Cannot autowire service ".service_locator.O4XFgzj": it references class "App\\Entity\\Agriculteur" but no such service exists.'],
        ], [
            'agriculteur' => 'App\\Entity\\Agriculteur',
        ]);
    }
}
