<?php

namespace ContainerRxbv6n5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bg1tx3RService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Bg1tx3R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bg1tx3R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repContact' => ['privates', 'App\\Repository\\ContactInfoRepository', 'getContactInfoRepositoryService', true],
        ], [
            'repContact' => 'App\\Repository\\ContactInfoRepository',
        ]);
    }
}
