<?php

namespace ContainerRxbv6n5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieImagesTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CategorieImagesType' shared autowired service.
     *
     * @return \App\Form\CategorieImagesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CategorieImagesType'] = new \App\Form\CategorieImagesType();
    }
}
