<?php

namespace ContainerRxbv6n5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\Admin\\AgriculteurType' => ['privates', 'App\\Form\\Admin\\AgriculteurType', 'getAgriculteurTypeService', true],
            'App\\Form\\Admin\\CategorieType' => ['privates', 'App\\Form\\Admin\\CategorieType', 'getCategorieTypeService', true],
            'App\\Form\\Admin\\RegistrationAdminFormType' => ['privates', 'App\\Form\\Admin\\RegistrationAdminFormType', 'getRegistrationAdminFormTypeService', true],
            'App\\Form\\Agriculteur\\ImagesCatType' => ['privates', 'App\\Form\\Agriculteur\\ImagesCatType', 'getImagesCatTypeService', true],
            'App\\Form\\Agriculteur\\RegistrationFormType' => ['privates', 'App\\Form\\Agriculteur\\RegistrationFormType', 'getRegistrationFormTypeService', true],
            'App\\Form\\Agriculteur\\UpdatePassFormType' => ['privates', 'App\\Form\\Agriculteur\\UpdatePassFormType', 'getUpdatePassFormTypeService', true],
            'App\\Form\\Agriculteur\\UpdateProfilFormType' => ['privates', 'App\\Form\\Agriculteur\\UpdateProfilFormType', 'getUpdateProfilFormTypeService', true],
            'App\\Form\\CategorieImagesType' => ['privates', 'App\\Form\\CategorieImagesType', 'getCategorieImagesTypeService', true],
            'App\\Form\\ChangePasswordFormType' => ['privates', 'App\\Form\\ChangePasswordFormType', 'getChangePasswordFormTypeService', true],
            'App\\Form\\ContactInfo\\ContactFormType' => ['privates', 'App\\Form\\ContactInfo\\ContactFormType', 'getContactFormTypeService', true],
            'App\\Form\\ContactType' => ['privates', 'App\\Form\\ContactType', 'getContactTypeService', true],
            'App\\Form\\FormExtension\\HoneyPotType' => ['privates', 'App\\Form\\FormExtension\\HoneyPotType', 'getHoneyPotTypeService', true],
            'App\\Form\\ResetPasswordRequestFormType' => ['privates', 'App\\Form\\ResetPasswordRequestFormType', 'getResetPasswordRequestFormTypeService', true],
            'App\\Form\\Trash\\RFT' => ['privates', 'App\\Form\\Trash\\RFT', 'getRFTService', true],
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => ['privates', 'liip_imagine.form.type.image', 'getLiipImagine_Form_Type_ImageService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\Admin\\AgriculteurType' => '?',
            'App\\Form\\Admin\\CategorieType' => '?',
            'App\\Form\\Admin\\RegistrationAdminFormType' => '?',
            'App\\Form\\Agriculteur\\ImagesCatType' => '?',
            'App\\Form\\Agriculteur\\RegistrationFormType' => '?',
            'App\\Form\\Agriculteur\\UpdatePassFormType' => '?',
            'App\\Form\\Agriculteur\\UpdateProfilFormType' => '?',
            'App\\Form\\CategorieImagesType' => '?',
            'App\\Form\\ChangePasswordFormType' => '?',
            'App\\Form\\ContactInfo\\ContactFormType' => '?',
            'App\\Form\\ContactType' => '?',
            'App\\Form\\FormExtension\\HoneyPotType' => '?',
            'App\\Form\\ResetPasswordRequestFormType' => '?',
            'App\\Form\\Trash\\RFT' => '?',
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
        }, 5), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
