<?php

namespace ContainerRxbv6n5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_UserappService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.userapp' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.authenticator.userapp'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([0 => ($container->privates['App\\Security\\AppUserAuthenticator'] ?? $container->load('getAppUserAuthenticatorService')), 1 => ($container->privates['security.authenticator.form_login.userapp'] ?? $container->load('getSecurity_Authenticator_FormLogin_UserappService'))], ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()), ($container->privates['security.event_dispatcher.userapp'] ?? $container->getSecurity_EventDispatcher_UserappService()), 'userapp', ($container->privates['monolog.logger.security'] ?? $container->getMonolog_Logger_SecurityService()), true, false, []));
    }
}
