<?php

namespace ContainerRxbv6n5;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_User_Provider_Concrete_AllUsersService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.user.provider.concrete.all_users' shared service.
     *
     * @return \Symfony\Component\Security\Core\User\ChainUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.user.provider.concrete.all_users'] = new \Symfony\Component\Security\Core\User\ChainUserProvider(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.user.provider.concrete.user_db'] ?? $container->load('getSecurity_User_Provider_Concrete_UserDbService'));
            yield 1 => ($container->privates['security.user.provider.concrete.backend_users'] ?? $container->load('getSecurity_User_Provider_Concrete_BackendUsersService'));
        }, 2));
    }
}
