<?php

namespace ContainerOJRYYZ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgriculteurRepositoryService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Repository\AgriculteurRepository' shared autowired service.
     *
     * @return \App\Repository\AgriculteurRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\AgriculteurRepository'] = new \App\Repository\AgriculteurRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
