<?php

namespace ContainerOJRYYZ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgriculteurTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\Admin\AgriculteurType' shared autowired service.
     *
     * @return \App\Form\Admin\AgriculteurType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Admin\\AgriculteurType'] = new \App\Form\Admin\AgriculteurType();
    }
}
