<?php

namespace ContainerOJRYYZ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategorieControllerService extends App_KernelDevContainer
{
    /*
     * Gets the public 'App\Controller\Admin\CategorieController' shared autowired service.
     *
     * @return \App\Controller\Admin\CategorieController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Admin\\CategorieController'] = $instance = new \App\Controller\Admin\CategorieController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Admin\\CategorieController', $container));

        return $instance;
    }
}
