<?php

namespace ContainerOJRYYZ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoneyPotTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\FormExtension\HoneyPotType' shared autowired service.
     *
     * @return \App\Form\FormExtension\HoneyPotType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\FormExtension\\HoneyPotType'] = new \App\Form\FormExtension\HoneyPotType(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
