<?php

namespace ContainerOJRYYZ4;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImagesCatTypeService extends App_KernelDevContainer
{
    /*
     * Gets the private 'App\Form\Agriculteur\ImagesCatType' shared autowired service.
     *
     * @return \App\Form\Agriculteur\ImagesCatType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Agriculteur\\ImagesCatType'] = new \App\Form\Agriculteur\ImagesCatType();
    }
}
