liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters: 
                thumbnail:
                    size:   [260, 180]
                    mode:   outbound
        thumbMedium:
            quality: 85
            filters:
                thumbnail: { size: [520, 310], mode: outbound }


                
