security:
    encoders:
        App\Entity\Agriculteur:
            algorithm: bcrypt
        App\Entity\Admin:
            algorithm: auto
            
    # https://symfony.com/doc/current/security/authenticator_manager.html
    enable_authenticator_manager: true

    hide_user_not_found: false
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users_in_memory: { memory: null }
        backend_users:
            entity:
                class: App\Entity\Admin
                property: username
        

        user_db:
            entity:
                class: App\Entity\Agriculteur
                property: email

        all_users:
            chain:
                providers: ['user_db', 'backend_users'] 



    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        userapp:
            lazy: true
            provider: all_users
            custom_authenticator:
                - App\Security\AppUserAuthenticator
            logout:
                path: app_logout
            form_login: 
                login_path: app_login  
                check_path: app_login
                enable_csrf: true
                
            entry_point: form_login
            user_checker: App\Security\EmailValidateChecker



            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/agriculteur, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]