<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRxbv6n5\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRxbv6n5/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRxbv6n5.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRxbv6n5\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRxbv6n5\App_KernelProdContainer([
    'container.build_hash' => 'Rxbv6n5',
    'container.build_id' => '1aebc119',
    'container.build_time' => 1682504641,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRxbv6n5');
