<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpP9LFM\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpP9LFM/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerRpP9LFM.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerRpP9LFM\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerRpP9LFM\App_KernelProdContainer([
    'container.build_hash' => 'RpP9LFM',
    'container.build_id' => '59b3e1bd',
    'container.build_time' => 1666533144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpP9LFM');
