<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGUSX6gN\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGUSX6gN/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerGUSX6gN.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerGUSX6gN\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerGUSX6gN\App_KernelProdContainer([
    'container.build_hash' => 'GUSX6gN',
    'container.build_id' => '1a9bd32b',
    'container.build_time' => 1650833247,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGUSX6gN');
