<?php

namespace ContainerK6bpeox;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XdpP7cSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xdpP7cS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xdpP7cS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'repContact' => ['privates', 'App\\Repository\\ContactInfoRepository', 'getContactInfoRepositoryService', true],
        ], [
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
            'repContact' => 'App\\Repository\\ContactInfoRepository',
        ]);
    }
}
