<?php

namespace ContainerK6bpeox;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationAdminFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Admin\RegistrationAdminFormType' shared autowired service.
     *
     * @return \App\Form\Admin\RegistrationAdminFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'Admin'.\DIRECTORY_SEPARATOR.'RegistrationAdminFormType.php';

        return $container->privates['App\\Form\\Admin\\RegistrationAdminFormType'] = new \App\Form\Admin\RegistrationAdminFormType();
    }
}
