<?php

namespace ContainerGUSX6gN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgriculteurService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.FVT1VGj.App\Entity\Agriculteur' shared service.
     *
     * @return \App\Entity\Agriculteur
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FVT1VGj": it references class "App\\Entity\\Agriculteur" but no such service exists.');
    }
}
