<?php

namespace ContainerGUSX6gN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAgriculteurController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Agriculteur\AgriculteurController' shared autowired service.
     *
     * @return \App\Controller\Agriculteur\AgriculteurController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Agriculteur\\AgriculteurController'] = $instance = new \App\Controller\Agriculteur\AgriculteurController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\Agriculteur\\AgriculteurController', $container));

        return $instance;
    }
}
