<?php

namespace ContainerGUSX6gN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationAdminFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Admin\RegistrationAdminFormType' shared autowired service.
     *
     * @return \App\Form\Admin\RegistrationAdminFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Admin\\RegistrationAdminFormType'] = new \App\Form\Admin\RegistrationAdminFormType();
    }
}
