<?php

namespace ContainerGUSX6gN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdatePassFormTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Agriculteur\UpdatePassFormType' shared autowired service.
     *
     * @return \App\Form\Agriculteur\UpdatePassFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Agriculteur\\UpdatePassFormType'] = new \App\Form\Agriculteur\UpdatePassFormType();
    }
}
