<?php

namespace ContainerDewtxhH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHoneyPotSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\HoneyPotSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\HoneyPotSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'HoneyPotSubscriber.php';

        return $container->privates['App\\EventSubscriber\\HoneyPotSubscriber'] = new \App\EventSubscriber\HoneyPotSubscriber(($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
