<?php

namespace ContainerRpP9LFM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppUserAuthenticatorService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AppUserAuthenticator' shared autowired service.
     *
     * @return \App\Security\AppUserAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\AppUserAuthenticator'] = new \App\Security\AppUserAuthenticator(($container->services['router'] ?? $container->getRouterService()));
    }
}
