<?php

namespace ContainerRpP9LFM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactInfoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContactInfoRepository' shared autowired service.
     *
     * @return \App\Repository\ContactInfoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContactInfoRepository'] = new \App\Repository\ContactInfoRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
