<?php

namespace ContainerRpP9LFM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.fzS6Lyj'] ?? $container->get_ServiceLocator_FzS6LyjService()), ($container->privates['.service_locator.nsnB.hL'] ?? $container->load('get_ServiceLocator_NsnB_HLService')), ['userapp' => [0 => ($container->privates['App\\Security\\AppUserAuthenticator'] ?? $container->load('getAppUserAuthenticatorService')), 1 => ($container->privates['security.authenticator.form_login.userapp'] ?? $container->load('getSecurity_Authenticator_FormLogin_UserappService'))]], true);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
