<?php

namespace ContainerRpP9LFM;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVisiteurControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\VisiteurController' shared autowired service.
     *
     * @return \App\Controller\VisiteurController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\VisiteurController'] = $instance = new \App\Controller\VisiteurController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\VisiteurController', $container));

        return $instance;
    }
}
