<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJUqqG8p\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJUqqG8p/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJUqqG8p.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJUqqG8p\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJUqqG8p\App_KernelDevDebugContainer([
    'container.build_hash' => 'JUqqG8p',
    'container.build_id' => 'cb0b83ac',
    'container.build_time' => 1682504657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJUqqG8p');
