<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDewtxhH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDewtxhH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDewtxhH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDewtxhH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDewtxhH\App_KernelDevDebugContainer([
    'container.build_hash' => 'DewtxhH',
    'container.build_id' => '29cc5db6',
    'container.build_time' => 1693515564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDewtxhH');
