<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0SDbij\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0SDbij/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ0SDbij.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ0SDbij\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ0SDbij\App_KernelDevDebugContainer([
    'container.build_hash' => 'J0SDbij',
    'container.build_id' => 'a40d7940',
    'container.build_time' => 1666534228,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0SDbij');
