<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agriculteur extends \App\Entity\Agriculteur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'nom_domaine', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'descriptif', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'confirm_password', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'disponible', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'Categorie', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'tel_portable', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'tel_fixe', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'activation_token'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'nom', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'nom_domaine', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'ville', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'code_postal', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'descriptif', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'password', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'confirm_password', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'disponible', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'Categorie', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'etat', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'tel_portable', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'tel_fixe', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'isVerified', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'images', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'photo', '' . "\0" . 'App\\Entity\\Agriculteur' . "\0" . 'activation_token'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agriculteur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNom(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom(string $nom): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomDomaine(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomDomaine', []);

        return parent::getNomDomaine();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomDomaine(string $nom_domaine): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomDomaine', [$nom_domaine]);

        return parent::setNomDomaine($nom_domaine);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', []);

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille(string $ville): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', [$ville]);

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', []);

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal(int $code_postal): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', [$code_postal]);

        return parent::setCodePostal($code_postal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptif', []);

        return parent::getDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptif(string $descriptif): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptif', [$descriptif]);

        return parent::setDescriptif($descriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword(string $password): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmPassword(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmPassword', []);

        return parent::getConfirmPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmPassword(string $confirm_password): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmPassword', [$confirm_password]);

        return parent::setConfirmPassword($confirm_password);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisponible(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisponible', []);

        return parent::getDisponible();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisponible(bool $disponible): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisponible', [$disponible]);

        return parent::setDisponible($disponible);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail(string $email): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function addCategorie(\App\Entity\Categorie $categorie): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategorie', [$categorie]);

        return parent::addCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCategorie(\App\Entity\Categorie $categorie): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCategorie', [$categorie]);

        return parent::removeCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserIdentifier(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserIdentifier', []);

        return parent::getUserIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelPortable(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelPortable', []);

        return parent::getTelPortable();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelPortable(?string $tel_portable): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelPortable', [$tel_portable]);

        return parent::setTelPortable($tel_portable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelFixe(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelFixe', []);

        return parent::getTelFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelFixe(?string $tel_fixe): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelFixe', [$tel_fixe]);

        return parent::setTelFixe($tel_fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function isVerified(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isVerified', []);

        return parent::isVerified();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsVerified(bool $isVerified): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsVerified', [$isVerified]);

        return parent::setIsVerified($isVerified);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', []);

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\App\Entity\Images $image): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', [$image]);

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\App\Entity\Images $image): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', [$image]);

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(?string $photo): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivationToken(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivationToken', []);

        return parent::getActivationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivationToken(?string $activation_token): \App\Entity\Agriculteur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivationToken', [$activation_token]);

        return parent::setActivationToken($activation_token);
    }

}
